services:
  - type: web
    name: nearlive
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "python create_superuser.py && gunicorn nearlive.wsgi:application"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
